import { defineGkdApp } from '@gkd-kit/define';

export default defineGkdApp({
  id: 'com.hunantv.imgo.activity',
  name: '芒果TV',
  groups: [
    {
      key: 1,
      name: '热启开屏广告',
      desc: '自动点击"跳过"',
      actionMaximum: 1,
      activityIds: 'com.mgtv.ui.ad.AdHotSplashActivity',
      fastQuery: true,
      rules: '[id="com.hunantv.imgo.activity:id/mgmi_ad_skip_text"]',
      snapshotUrls: 'https://i.gkd.li/i/18704697',
    },
    {
      key: 2,
      name: '冷启开屏广告',
      desc: '自动点击"跳过"',
      actionMaximum: 1,
      activityIds: '.MainActivity',
      fastQuery: true,
      rules: '[id="com.hunantv.imgo.activity:id/mgmi_ad_skip_text"]',
      snapshotUrls: 'https://i.gkd.li/i/18704715',
    },
    {
      key: 3,
      name: '视频内浮层广告',
      desc: '自动点击"关闭"',
      actionMaximum: 1,
      activityIds: 'com.mgtv.ui.videoplay.MGVideoPlayActivity',
      fastQuery: true,
      rules: '[id="com.hunantv.imgo.activity:id/closeAdIcon"]',
      snapshotUrls: 'https://i.gkd.li/i/18704720',
    },
    {
      key: 4,
      name: '青少年模式弹窗',
      desc: '自动点击"我知道了"',
      actionMaximum: 1,
      activityIds: '.MainActivity',
      fastQuery: true,
      rules: '[id="com.hunantv.imgo.activity:id/btnIknow"]',
      snapshotUrls: 'https://i.gkd.li/i/18717611',
    },
    {
      key: 5,
      name: '通知权限弹窗',
      desc: '自动点击"以后再说"',
      actionMaximum: 1,
      activityIds: '.MainActivity',
      fastQuery: true,
      rules: '[id="com.hunantv.imgo.activity:id/cancel"]',
      snapshotUrls: 'https://i.gkd.li/i/18717621',
    },
    {
      key: 6,
      name: '广告弹窗',
      desc: '自动点击"关闭"',
      actionMaximum: 1,
      activityIds: 'com.mgtv.ui.videoplay.MGVideoPlayActivity',
      fastQuery: true,
      rules: '[id="com.hunantv.imgo.activity:id/btnClose"]',
      snapshotUrls: 'https://i.gkd.li/i/18963292',
    },
    {
      key: 7,
      name: '下载页广告半屏',
      desc: '自动点击"关闭"',
      activityIds: 'com.mgtv.ui.download.DownloadActivity',
      fastQuery: true,
      rules: [
        {
          key: 0,
          name: '点击“广告”',
          matches: '[id="com.hunantv.imgo.activity:id/layout_logo"]',
          snapshotUrls: 'https://i.gkd.li/i/18963435',
        },
        {
          preKeys: [0],
          key: 1,
          name: '点击“关闭”',
          matches: '[id="com.hunantv.imgo.activity:id/close_ad"]',
          snapshotUrls: 'https://i.gkd.li/i/18963462',
        },
      ],
      snapshotUrls: 'https://i.gkd.li/i/18963292',
    },
    {
      key: 8,
      name: '播放页游戏弹窗',
      desc: '自动点击"关闭"',
      actionMaximum: 1,
      activityIds: 'com.mgtv.ui.videoplay.MGVideoPlayActivity',
      rules:
        '@TextView <2 View <2 View < View < WebView < WebView <2 [vid="container"]',
      snapshotUrls: 'https://i.gkd.li/i/18963292',
    },
  ],
});
